// <auto-generated />
namespace CodefirstFromDataBaseExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TelefoneCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TelefoneCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201904281301042_TelefoneCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
