//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDA
    {
        public int ID { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<int> PRODUTO { get; set; }
        public Nullable<System.DateTime> DATAVENDA { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual PRODUTO PRODUTO1 { get; set; }
    }
}
